services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090             # host:container
    restart: unless-stopped
    networks:
      - monitor-net
    volumes:
      - ./monitor/prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    networks:
      - monitor-net
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./monitor/grafana:/etc/grafana/provisioning/datasources

volumes:
  prom_data:

networks:
  monitor-net:
    driver: bridge
