apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: grafana-env
          image: grafana/grafana
          livenessProbe:
            exec:
              command:
                - wget
                - --spider
                - -q
                - http://localhost:3001
            failureThreshold: 5
            periodSeconds: 10
          name: grafana
          ports:
            - containerPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-cm0
            - mountPath: /grafana
              name: grafana-data
      restartPolicy: Always
      volumes:
        - configMap:
            name: grafana-cm0
          name: grafana-cm0
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
