definitions:
  model.CreateTaskRequest:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  model.Task:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        $ref: '#/definitions/model.TaskStatus'
      title:
        type: string
    type: object
  model.TaskStatus:
    enum:
    - pending
    - in-progress
    - completed
    - archived
    - deleted
    type: string
    x-enum-varnames:
    - Pending
    - InProgress
    - Completed
    - Archived
    - Deleted
  model.UpdateTaskRequest:
    properties:
      description:
        type: string
      status:
        $ref: '#/definitions/model.TaskStatus'
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/task:
    get:
      description: Retrieve a list of all tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all tasks
      tags:
      - task
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a new task
      tags:
      - task
  /api/task/{id}:
    delete:
      description: Delete a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Delete a task
      tags:
      - task
    get:
      description: Retrieve a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "404":
          description: Not Found
          schema: {}
      summary: Get task by ID
      tags:
      - task
    patch:
      consumes:
      - application/json
      description: Update the title, description, or status of a task
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Task Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Update a task
      tags:
      - task
swagger: "2.0"
